name: Hello Actions

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

  workflow_dispatch:
env:
  name: Janssen Lima
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      run: npm install
    - name: build
      run: npm run build
    - name: deploy
      uses: demurgos/ga-deploy-git@v1
      with: 
        accessToken: ${{ secrets.access_token }}
        srcDir: build
        destBranch: gh-pages
  cotacao:
    runs-on: ubuntu-latest
    env:
      formato: json
      par_moeda: ${{ secrets.moedas }}
    steps:
      - name: Cotacao moeda
        run: curl -s --url https://economia.awesomeapi.com.br/$formato/last/$par_moeda

  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  pull_request_only:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Hi, $name.
